# [1] 서버 포트 설정
server.port=8080

# [2] JSP 경로 설정
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# [3] Oracle DB 연결 정보 
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@192.168.0.6:1521:xe
spring.datasource.username=gomonth
spring.datasource.password=tiger

# 한글 깨짐 방지
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# MyBatis 매퍼 파일 위치 (프로젝트 구조에 맞게 수정)
mybatis.mapper-locations=classpath:mapper/*.xml
# DTO 패키지 경로
mybatis.type-aliases-package=com.gomonth.dto
