-- 9월 매핑
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F0901', 'fal01', 'fall', 9, 'Y');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F0902', 'fal02', 'fall', 9, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F0903', 'fal03', 'fall', 9, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F0904', 'fal04', 'fall', 9, 'N');

-- 10월 매핑
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1001', 'fal05', 'fall', 10, 'Y');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1002', 'fal06', 'fall', 10, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1003', 'fal07', 'fall', 10, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1004', 'fal08', 'fall', 10, 'N');

-- 11월 매핑 (백양사 Featured)
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1101', 'fal09', 'fall', 11, 'Y');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1102', 'fal10', 'fall', 11, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1103', 'fal11', 'fall', 11, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('F1104', 'fal12', 'fall', 11, 'N');

COMMIT;