-- 1. 회원 정보 (Users)
CREATE TABLE USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USER_PW VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE
);

-- 2. 여행지 마스터 (Places)
CREATE TABLE PLACES (
    PLACE_ID VARCHAR2(50) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(200),
    BANNER_IMG VARCHAR2(255),
    LIST_IMG VARCHAR2(255),
    SEASON_NOTE VARCHAR2(100)
);

-- 3. 시즌 및 월 매핑 (Place Seasons)
CREATE TABLE PLACE_SEASONS (
    SEASON_ID NUMBER PRIMARY KEY,
    PLACE_ID VARCHAR2(50) REFERENCES PLACES(PLACE_ID),
    SEASON_TYPE VARCHAR2(20),
    MONTH_VAL NUMBER(2),
    IS_FEATURED CHAR(1) CHECK (IS_FEATURED IN ('Y', 'N'))
);

-- 4. 상세 가이드 포인트 (Place Tips)
CREATE TABLE PLACE_TIPS (
    TIP_ID NUMBER PRIMARY KEY,
    PLACE_ID VARCHAR2(50) REFERENCES PLACES(PLACE_ID),
    ORDER_NO NUMBER(2),
    CONTENT VARCHAR2(1000)
);

-- 5. 찜 목록 (Favorites)
CREATE TABLE FAVORITES (
    FAV_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) REFERENCES USERS(USER_ID),
    PLACE_ID VARCHAR2(50) REFERENCES PLACES(PLACE_ID),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- 6. 문의 사항 (Inquiries)
CREATE TABLE INQUIRIES (
    INQ_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) REFERENCES USERS(USER_ID),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    STATUS VARCHAR2(20) DEFAULT '접수',
    CREATED_AT DATE DEFAULT SYSDATE
);