-- [PLACE_SEASONS] 12월 상세 매핑
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S1201', 'win01', 'winter', 12, 'Y');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S1202', 'win02', 'winter', 12, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S1203', 'win03', 'winter', 12, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S1204', 'win04', 'winter', 12, 'N');

-- [PLACE_SEASONS] 1월 상세 매핑
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0101', 'win05', 'winter', 1, 'Y');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0102', 'win06', 'winter', 1, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0103', 'win07', 'winter', 1, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0104', 'win08', 'winter', 1, 'N');

-- [PLACE_SEASONS] 2월 상세 매핑
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0201', 'win09', 'winter', 2, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0202', 'win10', 'winter', 2, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0203', 'win11', 'winter', 2, 'N');
INSERT INTO PLACE_SEASONS (SEASON_ID, PLACE_ID, SEASON_TYPE, MONTH_VAL, IS_FEATURED) VALUES ('S0204', 'win12', 'winter', 2, 'Y');

COMMIT;