CREATE TABLE USERS ( /* 회원정보 */
    USER_ID NUMBER(4) PRIMARY KEY, /* 회원ID */
    USER_NAME VARCHAR2(50),  /* 회원명 */
    PASSWORD VARCHAR2(10),   /* 비밀번호 */
    EMAIL VARCHAR2(50),      /* 이메일 */
    ADDRESS VARCHAR2(100),   /* 주소 */
    REG_DATE DATE            /* 등록일자 */
);
DROP TABLE INQUIRIES;
CREATE TABLE INQUIRIES ( /* 문의정보 */
    INQUIRY_ID NUMBER(10) PRIMARY KEY, /* 문의번호 */
    USER_ID NUMBER(4),         /* 회원ID */
    INQUIRY_TYPE VARCHAR2(50), /* 질문유형 */
    CONTENT VARCHAR2(1000),    /* 내용 */
    REG_DATE DATE              /* 등록일자 */
);
CREATE TABLE TRAVEL ( /* 여행지정보 */
    TRAVEL_ID NUMBER(4) PRIMARY KEY, /* 여행지ID */
    TRAVEL_NAME VARCHAR2(50),   /* 여행지명 */
    REGION VARCHAR2(100),       /* 지역 */
    DESCRIPTION VARCHAR2(1000), /* 내용 */
    ADDRESS VARCHAR2(100),      /* 주소 */
    MONTH NUMBER(2),            /* 대상월 */
    FILE_NAME VARCHAR2(50),     /* 파일명 */
    REG_DATE DATE               /* 등록일자 */
);
CREATE TABLE ADDITIONAL_INFO_TYPE ( /* 부가정보유형 */
    INFO_TYPE_ID VARCHAR2(10) PRIMARY KEY, /* 정보유형ID */
    INFO_TYPE_NAME VARCHAR2(50), /* 정보유형명 */
    REG_DATE DATE                /* 등록일자 */
);
CREATE TABLE TRAVEL_ADDITIONAL_INFO ( /* 여행부가정보 */
    INFO_ID NUMBER(10) PRIMARY KEY, /* 부가정보ID */
    TRAVEL_ID NUMBER(4),       /* 여행지ID */
    INFO_TYPE_ID VARCHAR2(10), /* 정보유형ID */
    CONTENT VARCHAR2(1000),    /* 내용 */
    REG_DATE DATE              /* 등록일자 */
);
CREATE TABLE FAVORITES ( /* 찜정보 */
    FAVORITE_ID NUMBER(10) PRIMARY KEY, /* 찜ID */
    USER_ID NUMBER(4),   /* 회원ID */
    TRAVEL_ID NUMBER(4), /* 여행지ID */
    REG_DATE DATE        /* 등록일자 */
);
/* 회원정보 */
INSERT INTO USERS VALUES(1111, '홍길동', 'pass1111', 'hong@site.com', '', SYSDATE);
INSERT INTO USERS VALUES(1112, '마길동', 'pass1112', 'ma@site.com', '', SYSDATE);
INSERT INTO USERS VALUES(1113, '신길동', 'pass1113', 'shin@site.com', '', SYSDATE);
INSERT INTO INQUIRIES VALUES(111, 1111, '장소문의', '내가 좋아하는 여행지가 어디일까요', SYSDATE);
INSERT INTO INQUIRIES VALUES(112, 1112, '상태문의', '내가 좋아하는 여행지가 청결한가요', SYSDATE);
INSERT INTO INQUIRIES VALUES(113, 1113, '소요시간문의', '내가 좋아하는 여행지가 소요시간이 궁금합니다.', SYSDATE);
INSERT INTO TRAVEL VALUES(11, '경주여행', '경주', '경주일주', '경상북도경주시', 12, '', SYSDATE);
INSERT INTO TRAVEL VALUES(12, '목포여행', '목포', '목포일주', '전라남도목포시', 1, '', SYSDATE);
INSERT INTO TRAVEL VALUES(13, '제주여행', '제주', '제주일주', '제주도제주시', 2, '', SYSDATE);
INSERT INTO ADDITIONAL_INFO_TYPE VALUES('A', '맛집', SYSDATE);
INSERT INTO ADDITIONAL_INFO_TYPE VALUES('B', '숙소', SYSDATE);
INSERT INTO ADDITIONAL_INFO_TYPE VALUES('C', '체험', SYSDATE);
INSERT INTO TRAVEL_ADDITIONAL_INFO VALUES(1, 11, 'A', '매우 맛있습니다', SYSDATE);
INSERT INTO TRAVEL_ADDITIONAL_INFO VALUES(2, 12, 'B', '매우 좋은 숙소입니다', SYSDATE);
INSERT INTO TRAVEL_ADDITIONAL_INFO VALUES(3, 13, 'C', '매우 활동적인 체험입니다', SYSDATE);
INSERT INTO FAVORITES VALUES(1, 1111, 11, SYSDATE);
INSERT INTO FAVORITES VALUES(2, 1112, 12, SYSDATE);
INSERT INTO FAVORITES VALUES(3, 1113, 13, SYSDATE);
SELECT USER_ID, USER_NAME, PASSWORD, EMAIL, ADDRESS, REG_DATE FROM USERS WHERE USER_ID = 1111;
SELECT INQUIRY_ID, USER_ID, INQUIRY_TYPE, CONTENT, SYSDATE FROM INQUIRIES;
SELECT TRAVEL_ID, TRAVEL_NAME, REGION, DESCRIPTION, ADDRESS, MONTH, FILE_NAME, SYSDATE FROM TRAVEL;
SELECT INFO_TYPE_ID, INFO_TYPE_NAME, SYSDATE FROM ADDITIONAL_INFO_TYPE;
SELECT INFO_ID, TRAVEL_ID, INFO_TYPE_ID, CONTENT, SYSDATE FROM TRAVEL_ADDITIONAL_INFO;
SELECT FAVORITE_ID, USER_ID, TRAVEL_ID, SYSDATE FROM FAVORITES;
