-- 1️⃣ 기존 테이블 삭제 (존재하면 삭제)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE destination_desc CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE destination_images CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE destinations CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 2️⃣ 테이블 생성
CREATE TABLE destinations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id VARCHAR2(20),
    month NUMBER,
    title VARCHAR2(100),
    short_desc VARCHAR2(200),
    location VARCHAR2(100),
    visit_season VARCHAR2(50),
    is_featured NUMBER DEFAULT 0
);

CREATE TABLE destination_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id NUMBER REFERENCES destinations(id),
    image_url VARCHAR2(200),
    description VARCHAR2(200)
);

CREATE TABLE destination_desc (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id NUMBER REFERENCES destinations(id),
    text VARCHAR2(400)
);

-- 3️⃣ 데이터 INSERT 
-- 3월
INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season, is_featured)
VALUES ('spring', 3, '3월 봄 대표 여행지','산수유·매화·유채꽃','전국','3월',1);

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 3, '구례 산수유 마을','노란 산수유 꽃','전남 구례','3월');

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 3, '제주도 유채꽃 시즌','노란 유채꽃','제주도','3월');

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 3, '광양 매화마을','흰 매화꽃','전남 광양','3월');

-- 4월
INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season, is_featured)
VALUES ('spring', 4, '4월 봄 대표 여행지','벚꽃·완연한 봄','전국','4월',1);

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 4, '경주 영지 둘레길','벚꽃 산책','경주','4월');

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 4, '진해군 벚꽃축제','축제·포토존','진해','4월');

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 4, '담양 죽녹원','대나무 숲 산책','담양','4월');

-- 5월
INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season, is_featured)
VALUES ('spring', 5, '5월 봄 대표 여행지','신록/초록, 피크닉/트레킹','전국','5월',1);

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 5, '전남 다원 보성녹차밭','푸른 차밭','전남 보성','5월');

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 5, '메타세콰이어길 담양','푸른 길 산책','담양','5월');

INSERT INTO destinations(season_id, month, title, short_desc, location, visit_season)
VALUES ('spring', 5, '한라산 철쭉','분홍 철쭉꽃','제주도','5월');



SELECT table_name
FROM user_tables;



SELECT id, season_id, month, title, short_desc, location, visit_season, is_featured
FROM destinations
ORDER BY month, id;



SELECT id, destination_id, image_url, description
FROM destination_images
ORDER BY destination_id, id;



SELECT id, destination_id, text
FROM destination_desc
ORDER BY destination_id, id;


-- 4월 여행지 확인
SELECT * 
FROM destinations
WHERE month = 4;



SELECT owner, table_name
FROM all_tables
WHERE table_name IN ('DESTINATIONS','DESTINATION_IMAGES','DESTINATION_DESC');